### ISSUE TITLE
Update Instructions and Messages 

### ISSUE THREAD

**Issue by aqdasrehman** [amir-qayyum-khan/edx-platform#18]
Please add New set of Instructions and messages on the places mentioned in the below images:
![screen shot 2017-02-03 at 8 03 30 pm](https://cloud.githubusercontent.com/assets/13884387/22596058/ddc4a468-ea4b-11e6-8014-613e78ac1d20.png)

You have submitted your timed exam
Within the next two weeks, someone from the HR department will get in touch with you. Incase you do not make it to the next round, you will be informed via e-mail.

![screen shot 2017-02-03 at 8 04 23 pm](https://cloud.githubusercontent.com/assets/13884387/22596089/011ba66e-ea4c-11e6-84d0-33f2e8d15d13.png)

Change time to 1 hour and 40 minutes
This test has a time limit associated with it. To pass this test, you must complete the problems in the time allowed. Your time starts exactly at 3:00pm. No additional time will be allowed.
(remove all other information like “can i request additional time etc)
Instead of “i am ready to start this timed exam” write “Start Test”

**Comment by aqdasrehman** [comment]
Test instructions are updated from my side, please check messages text and update them @amir-qayyum-khan

**Comment by amir-qayyum-khan** [comment]
Done

**Comment by aqdasrehman** [comment]
Duplicate of Issue#54. Closing
