### ISSUE TITLE
Finalize Registration Form 

### ISSUE THREAD

**Issue by aqdasrehman** [amir-qayyum-khan/edx-platform#2]
Please finalize registration form design and functionality.

**Comment by amir-qayyum-khan** [comment]
on register, enroll user to course

**Comment by amir-qayyum-khan** [comment]
@aqdasrehman please verify it, log bugs here and assign back to @wajeeha-khalid wajeeha

**Comment by aqdasrehman** [comment]
@wajeeha-khalid  Validation required on the form, you can see I can put any data in any field
See screenshot (Firefox):
![screen shot 2017-02-06 at 10 21 05 pm](https://cloud.githubusercontent.com/assets/13884387/22658088/ae176a90-ecba-11e6-9600-3475b452537a.png)
and also for graduating year date format is not showing in Firefox while on chrome its showing
Screenshot: (Chrome)
![screen shot 2017-02-06 at 10 28 59 pm](https://cloud.githubusercontent.com/assets/13884387/22658417/cc50edd2-ecbb-11e6-86cf-f963e8dfc6fa.png)

**Comment by aqdasrehman** [comment]
On hover dropdown for calendar is also missing 
Screenshot: (Chrome)

![screen shot 2017-02-06 at 11 49 30 pm](https://cloud.githubusercontent.com/assets/13884387/22661528/7e31d704-ecc7-11e6-94cf-1b1f8edde4ee.png)

**Comment by aqdasrehman** [comment]
This is done. Closing.
