### ISSUE TITLE
Only show Submit button

### ISSUE THREAD

**Issue by aqdasrehman** [amir-qayyum-khan/edx-platform#20]
Only show Submit button on questions, currently there are 2 buttons of final check and Save, 
See screenshot :

![screen shot 2017-02-04 at 3 40 57 am](https://cloud.githubusercontent.com/assets/13884387/22611377/f7cfeed6-ea8b-11e6-9ca2-b19c72abe95d.png)

**Comment by amir-qayyum-khan** [comment]
please verify

**Comment by aqdasrehman** [comment]
This is done. Closing
