### ISSUE TITLE
Subsection Basic and Advanced settings are missing

### ISSUE THREAD

**Issue by aqdasrehman** [amir-qayyum-khan/edx-platform#21]
Subsection Basic and Advanced setting tabs are missing due to which I am unable to make timed exam, This is a **HIGH** priority issue need to fix soon, so that we can make timed exams. 
The 500 error previously on the course may be because of these settings.
See screenshot:

![screen shot 2017-02-05 at 12 52 33 am](https://cloud.githubusercontent.com/assets/13884387/22621113/a0e6a9d6-eb3d-11e6-8799-92d18173122f.png)

**Comment by amir-qayyum-khan** [comment]
Fixed please verify http://54.86.197.122:18010/

**Comment by aqdasrehman** [comment]
Fixed, closing this issue.
