### ISSUE TITLE
Hide about page from course

### ISSUE THREAD

**Issue by amir-qayyum-khan** [amir-qayyum-khan/edx-platform#23]

**Comment by amir-qayyum-khan** [comment]
Done, please verify

**Comment by aqdasrehman** [comment]
Yes About page is hidden but still the landing page is about page, which is not correct. See attachment:

![screen shot 2017-02-08 at 2 29 49 pm](https://cloud.githubusercontent.com/assets/13884387/22731094/3fe30532-ee0b-11e6-9553-98d2cdbc3bf3.png)

Student should directly land on Course/Exam page instead to select Course tab

**Comment by amir-qayyum-khan** [comment]
yes, if student has link he can go, who will care to use link for description because they are fresh grad. Please make sure there should not link for info page in app. Direct link is ok

**Comment by aqdasrehman** [comment]
Fixed. Closing
