### ISSUE TITLE
Show count down to test start on branding page

### ISSUE THREAD

**Issue by amir-qayyum-khan** [amir-qayyum-khan/edx-platform#24]

**Comment by amir-qayyum-khan** [comment]
just added number of days left for course start

<img width="760" alt="screen shot 2017-02-08 at 2 56 16 am" src="https://cloud.githubusercontent.com/assets/10431250/22713429/33eb755e-edaa-11e6-9caa-d1ceaa18907d.png">

**Comment by amir-qayyum-khan** [comment]
Please suggest me good message here
``2 days left`` => `Exam start in 2 days` ?

**Comment by aqdasrehman** [comment]
Can you ask Ayesha about message?

**Comment by aqdasrehman** [comment]
This course is not yet end, wrong text displaying. See attachment 
![screen shot 2017-02-08 at 7 10 23 pm](https://cloud.githubusercontent.com/assets/13884387/22740731/a2a4bd24-ee32-11e6-833b-211dab0a4be8.png)

**Comment by amir-qayyum-khan** [comment]
Made text like
- Test start in 2 day(s)
- Test start in 2 hour(s)
- Test start in 2 min(s)

according to time left
<img width="779" alt="screen shot 2017-02-09 at 3 08 28 pm" src="https://cloud.githubusercontent.com/assets/10431250/22778692/ad823e22-eed9-11e6-95be-86d9ab8e6729.png">

**Comment by aqdasrehman** [comment]
This is not yet done.

**Comment by amir-qayyum-khan** [comment]
25 Feb 3: 00 PM PKT

edx-platform/themes/arbisoft-nda/lms/templates/index.html

**Comment by noraiz-anwar** [comment]
PR https://github.com/amir-qayyum-khan/edx-platform/pull/86

**Comment by aqdasrehman** [comment]
Done. Closing
