### ISSUE TITLE
please suggest arbisoft invitation email instructions

### ISSUE THREAD

**Issue by amir-qayyum-khan** [amir-qayyum-khan/edx-platform#26]
@aqdasrehman please suggest arbisoft invitation email instructions.
This will be email that HR will send grads and provide them link of our site and will ask her to register

**Comment by aqdasrehman** [comment]
Message conveyed to Ayesha and text to change is in a doc. Feel free to open this issue again if anything else come in your mind @amir-qayyum-khan

**Comment by aqdasrehman** [comment]
This is done. Closing
