### ISSUE TITLE
get user profile from system

### ISSUE THREAD

**Issue by amir-qayyum-khan** [amir-qayyum-khan/edx-platform#28]
Way to get csv file of user data
```update /instructor#view-data_download```
there is already button for download profile, we need to update query to incorporate survey data 

<img width="1147" alt="screen shot 2017-02-08 at 3 44 30 pm" src="https://cloud.githubusercontent.com/assets/10431250/22733906/88a9600e-ee15-11e6-820f-0c145036d2cc.png">

**Comment by wajeeha-khalid** [comment]
@aqdasrehman Please Verify

**Comment by aqdasrehman** [comment]
@wajeeha-khalid I am unable to see student profile info csv file and even not seen any file in Pending Tasks, see attachment : 

![2017-02-12_0034](https://cloud.githubusercontent.com/assets/13884387/22856809/1a91ca9a-f0bb-11e6-9ab9-2e181883f47e.png)

**Comment by wajeeha-khalid** [comment]
@aqdasrehman We have not used this feature to download data. U can download all profile information in admin app via 'CSV Download' action.
Kindly test on admin app.

**Comment by zubair-arbi** [comment]
@amir-qayyum-khan I have added a [PR](https://github.com/amir-qayyum-khan/edx-platform/pull/95) to add CSV generation functionality on `Instructor Dashboard`. Please verify the changes.

**Comment by aqdasrehman** [comment]
This is done, getting results. Closing
