### ISSUE TITLE
Hide immediate result from student also hide Progress bar

### ISSUE THREAD

**Issue by aqdasrehman** [amir-qayyum-khan/edx-platform#3]
Hide immediate result i.e Correct/wrong from student during test so that student couldn't stuck in results stress during test. 

See attachment 

![16441594_1742316059127446_1008868594_n](https://cloud.githubusercontent.com/assets/13884387/22508400/8ab697c8-e8ab-11e6-9e20-7648ba1415bb.png)

**Comment by amir-qayyum-khan** [comment]
please verify

**Comment by aqdasrehman** [comment]
Done.
