### ISSUE TITLE
change time zone to Pakistan time

### ISSUE THREAD

**Issue by aqdasrehman** [amir-qayyum-khan/edx-platform#31]
Change the time zones to Pakistani time zone so that we can set date & time correctly.

**Comment by amir-qayyum-khan** [comment]
@aqdasrehman you need to convert PKT (4:00 pm) into UTC (11: 00 am) and have to add it in `Course Start Time` inside `Schedule & Details` studio


- http://edx.readthedocs.io/projects/edx-guide-for-students/en/latest/SFD_introduction.html
- http://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/set_up_course/scheduling_course.html#course-start-date-and-time

> dX recommends that you set the start time of your course early in the day, generally 00:00 UTC or earlier. Learners often expect the course to be available on the start date in their own time zones and try to access course content during the day. If you do not specify a start time for your course, learners see the default start time, 00:00 Coordinated Universal Time (UTC). The course start time and other course dates and times are displayed in learners’ own time zones, if they have specified a time zone in account settings.

**Comment by aqdasrehman** [comment]
@amir-qayyum-khan yes this was done already. Thanks! Closing
