### ISSUE TITLE
Change Learn More button to Enroll on dashboard

### ISSUE THREAD

**Issue by aqdasrehman** [amir-qayyum-khan/edx-platform#33]
On dashboard change the Learn More button to Enroll button and redirect user to Sign up/Create account page.
See attachment:

![screenshot 2017-02-08_20-01-55](https://cloud.githubusercontent.com/assets/13884387/22750155/8be211e4-ee51-11e6-8fa0-613d3b7da744.png)

**Comment by amir-qayyum-khan** [comment]
Done

**Comment by aqdasrehman** [comment]
Its OK for now to navigate student to Sign In page. Closing
