### ISSUE TITLE
Change content of activation email

### ISSUE THREAD

**Issue by amir-qayyum-khan** [amir-qayyum-khan/edx-platform#35]
https://docs.google.com/document/d/1-_-2GUKSzLNvew4xbFF0yChXRvCjuvWEpapNgQWICfg/edit

**Comment by amir-qayyum-khan** [comment]
Complete

**Comment by aqdasrehman** [comment]
Still there is some text that needs to be change @wajeeha-khalid 

**Current Email**

Thank you for creating an account with Arbisoft Fresh Hiring Platform! 

There's just one more step before you can enroll in a course: you need to activate your Arbisoft Fresh Hiring Platform account. To activate your account, click the following link. If that doesn't work, copy and paste the link into your browser's address bar. 

http://test.arbisoft.com/activate/0515a0a46e3847608c1d7fba7b5508b4 
If you didn't create an account, you don't need to do anything; you won't receive any more email from us. If you need assistance, please do not reply to this email message. Check the help section of the Arbisoft Fresh Hiring Platform website.

**Text should be**
Thank you for creating an account with Arbisoft Fresh Hiring Platform!

There's just one more step before you can enroll in the test, you need to activate your Arbisoft Fresh Hiring Platform account. To activate your account, click the following link:

  http://test.arbisoft.com/activate/a10ff19afccf4eed9982e3160d289e2a

If that doesn't work, copy and paste the link into your browser's address bar.

Good Luck!

Regards, 
Arbisoft HR

**Comment by wajeeha-khalid** [comment]
@amir-qayyum-khan  did you update deployement with latest change?

**Comment by wajeeha-khalid** [comment]
@aqdasrehman Please verify

**Comment by aqdasrehman** [comment]
This is done. Closing.
