### ISSUE TITLE
Hide Progress from everywhere

### ISSUE THREAD

**Issue by aqdasrehman** [amir-qayyum-khan/edx-platform#4]
@amir-qayyum-khan We need to hide progress from everywhere i.e progress tab and from timed exam page after ending the exam.

I have already hide tab progress for the course

https://docs.google.com/document/d/1w5sxuX4EtB6ZoRQ1pcF8xJW2w1AJ9BdJldLIHG0fzjo/edit?ts=58948eb4

**Comment by amir-qayyum-khan** [comment]
please provide me cms url of course @aqdasrehman

**Comment by aqdasrehman** [comment]
Here is the link to CMS : http://54.86.197.122:18010/course/course-v1:Arbisoft+Hiring_1+2017_1

**Comment by amir-qayyum-khan** [comment]
Done

**Comment by aqdasrehman** [comment]
Thanks. Closing
