### ISSUE TITLE
Feedback From Yasser Bhai

### ISSUE THREAD

**Issue by wajeeha-khalid** [amir-qayyum-khan/edx-platform#41]
**#Main Page:**

- [x] DONE

**1. change 'start' to 'starts'**   

- [x] DONE

**2. show time along with days (_ days _ hrs _min)** 

**Create Account/Registration:**

- [x] DONE

**1. Remove "Tell us why you're interested in Arbisoft Fresh Hiring Platform"** 

- [x] DONE

**2. Change "Arbisoft Fresh Hiring Platform" to "Arbisoft Hiring"**  

- [x] DONE

**3. Remove terms of service** 

- [x] DONE

4. Bold and rephrase Honor code "I have read Arbisoft Hiring's Honor Code" 

**Activate Page:**

- [x] DONE

1. Change text 

**Survey Form:**

- [x] DONE

**1. Rename "Position in class" to "Position/Rank in class" and make it optional** 

- [x] DONE

**2. Make "Position/Rank in class" Number input and update label with "(for example 1, 3, 10 etc)"**  

- [x] DONE

2. Rephrase "univeristy projects to" "Tell us about your 2 major projects" 

- [x] DONE

**3. Remove "any" from extracurricular activities (its redundant with if any)** 

- [x] DONE

**4. In freelance work question replace slash (/) with  'or'** 

- [x] DONE

**5. Batch mates to Batchmates** 

- [x] DONE

**6. Rephrase "Why Arbisoft" to "Why would you like to join Arbisoft"** 

- [x] DONE

**7. Remove 'Other' checkbox from Studied Courses and Technologies** 

- [x] DONE

**8. Remove 'Intro to Computing', 'Computer Network', 'Bio informatics', 'Comp Organization' from Studied courses and Expertise** 

- [x] DONE

**9. 'Other Studied Course' and 'Other Technolgies' -> add 'Comma Separated'** 

- [x] DONE

**9. Change Technolgies to: -** 

- Web Development
- Mobile Development (Android)
- Mobile Development (iOS)
- Data Science / Machine Learning 

- [x] DONE

10. Rephare Rank Expertise question 

- [x] DONE

11. Session timed out when took time on profile details form. Should not expire. 

**After Survey Submit page:** 

- [x] DONE

1. Remove Arbisoft Hriing_1 

- [x] DONE

2. Add Date with Day and remove UTC 

- [x] DONE

3. Change Image

**Comment by aqdasrehman** [comment]
1. **PENDING** Bold and rephrase Honor code "I have read Arbisoft Hiring's Honor Code", this is not Done

2. **PENDING** Change Text, which text ?

3. **PENDING** Rephrase "univeristy projects to" "Tell us about your 2 major projects", Spelling of Major needs to correct

4. **PENDING** Rephrase Rank Expertise question, what was changed in text?

5. **PENDING** Session timed out when took time on profile details form. Should not expire.

**Comment by wajeeha-khalid** [comment]
@aqdasrehman 
1. Rephrase has been done; will bold text.
2. After activation landing page text was:
"Visit your dashboard to see your courses."
updated to:
"Visit your dashboard."
3. Will do
4. "Mark the courses you are an expert at scale of 1 to 5, where 5 being expert and 1 being the least expert"
updated to
"Mark the courses you are an expert at on a scale of 1 to 5 (5 being the most and 1 being the least expert)"
5. Thats what you need to confirm; even after 30 mins waiting time the profile details form submits just fine.

**Comment by aqdasrehman** [comment]
This is Done. Closing
