### ISSUE TITLE
Update terms and services

### ISSUE THREAD

**Issue by aqdasrehman** [amir-qayyum-khan/edx-platform#42]
@wajeeha-khalid please update terms and services for our platform.

**Comment by wajeeha-khalid** [comment]
Arbisoft's Honor Code
https://docs.google.com/document/d/1DoDLLO2nfbfrMBPJgwP0jcOx-CgrzMb71J3XRwIr7_k/edit

**Comment by wajeeha-khalid** [comment]
@amir-qayyum-khan I have added text for honor code in honor.html. Please get the design fixed for the page.

**Comment by aqdasrehman** [comment]
This is Done. Closing
