### ISSUE TITLE
Name and Username hint text update

### ISSUE THREAD

**Issue by aqdasrehman** [amir-qayyum-khan/edx-platform#45]
Please update Full name* and Public username* hint text, see attachment:

![00000188](https://cloud.githubusercontent.com/assets/13884387/22827747/33d577e6-efbb-11e6-810b-2213429c9c03.png)

**Comment by wajeeha-khalid** [comment]
@aqdasrehman Please suggest text for hints or may be coordinate with Ayesha to get exact text to be displayed.

**Comment by aqdasrehman** [comment]
Done. Closing
