### ISSUE TITLE
list down your top two projects, needs rephrasing (registration form)

### ISSUE THREAD

**Issue by aqdasrehman** [amir-qayyum-khan/edx-platform#46]
We need rephrasing in this field, ask ayesha about the exact question. See screenshot:

![2017-02-10_1807](https://cloud.githubusercontent.com/assets/13884387/22827967/701d6d8e-efbc-11e6-9a83-2fbe94f21f63.png)

**Comment by wajeeha-khalid** [comment]
This is already a part of change requested by Yasser and is implemented in [this PR](https://github.com/amir-qayyum-khan/edx-platform/pull/43) which is not yet merged

**Comment by aqdasrehman** [comment]
Duplicate. Closing
