### ISSUE TITLE
Remove tell us why you are interested in Arbisoft hiring field

### ISSUE THREAD

**Issue by aqdasrehman** [amir-qayyum-khan/edx-platform#48]
This field should be removed, see screenshot:

![2017-02-10_1821](https://cloud.githubusercontent.com/assets/13884387/22828251/08ef7394-efbe-11e6-9c9e-70a85114d1e2.png)

**Comment by wajeeha-khalid** [comment]
This is already a part of change requested by Yasser and is implemented in [this PR](https://github.com/amir-qayyum-khan/edx-platform/pull/43) which is not yet merged

**Comment by aqdasrehman** [comment]
Duplicate. Closing
