### ISSUE TITLE
when submitting unfilled , the scale are reset to 1

### ISSUE THREAD

**Issue by aqdasrehman** [amir-qayyum-khan/edx-platform#53]
Ask ayesha for details

**Comment by aqdasrehman** [comment]
Form scale values reset on submitting after some fields were empty.

**Comment by wajeeha-khalid** [comment]
@amir-qayyum-khan Please review [PR](https://github.com/amir-qayyum-khan/edx-platform/pull/67) and let me know if its fine. I will merge it.

**Comment by aqdasrehman** [comment]
This is done. Closing
