### ISSUE TITLE
Timed exam content: to pass this “test”

### ISSUE THREAD

**Issue by aqdasrehman** [amir-qayyum-khan/edx-platform#54]
- [x] DONE

 timed exam messages we need to replace word "exam" with "test" and 'problems' with "Questions"
see attachment:

![2017-02-11_0126](https://cloud.githubusercontent.com/assets/13884387/22843022/745e9b56-eff9-11e6-8a8f-0e4af3d66fb4.png)

**Comment by aqdasrehman** [comment]
- [x] DONE
rephrase: submit my timed exam to submit my timed “test”

![2017-02-11_0229](https://cloud.githubusercontent.com/assets/13884387/22844905/1fd4dfba-f002-11e6-8e09-ee50e7c84b0a.png)

**Comment by aqdasrehman** [comment]
- [x] DONE

 my exam should be rephrases to end my “test”

![2017-02-11_0231](https://cloud.githubusercontent.com/assets/13884387/22844959/4f2db71e-f002-11e6-98bd-d2ace30b746d.png)

**Comment by aqdasrehman** [comment]
- [x] DONE

you have submitted your timed “test”, not exam

**Comment by wajeeha-khalid** [comment]
@amir-qayyum-khan Here is the PR for this issue:
https://github.com/amir-qayyum-khan/edx-proctoring/pull/2

**Comment by aqdasrehman** [comment]
- [ ] PENDING

Sorry to mention this text points before, but there are two places where this text "Exam" is still showing. Can you please change this too @wajeeha-khalid 

![2017-02-13_2325](https://cloud.githubusercontent.com/assets/13884387/22897107/3f29f1a4-f244-11e6-96a7-0c3242fcda61.png)

**Comment by wajeeha-khalid** [comment]
We are leaving left panel "exam" as is for now; this change will take time and is minor to block this to go to prod

**Comment by aqdasrehman** [comment]
This is done. Closing
