### ISSUE TITLE
Selected/Attempted/Non Attempted question colors

### ISSUE THREAD

**Issue by aqdasrehman** [amir-qayyum-khan/edx-platform#58]
the Qs skipped should be highlighted in some color so that one can go there again. the current Question i am on should also be highlighted

**Comment by aqdasrehman** [comment]
Or may be clicking on the Submit will automatically move to next question.

**Comment by aqdasrehman** [comment]
Selected color remains same as white, Attempted color as Green.

**Comment by naeem91** [comment]
Changes made. Please verify

**Comment by aqdasrehman** [comment]
I think this is not yet done. Because submitting questions not changing colors, I can't recognise which one submitted 
![2017-02-14_0225](https://cloud.githubusercontent.com/assets/13884387/22904118/012fba0a-f25d-11e6-99d7-a6814bf84601.png)

**Comment by naeem91** [comment]
@aqdasrehman sorry wasn't merged back then. Please verify now

**Comment by aqdasrehman** [comment]
Done. Closing
