### ISSUE TITLE
Edit the title “course” to “exam” 

### ISSUE THREAD

**Issue by aqdasrehman** [amir-qayyum-khan/edx-platform#6]
Please change the landing page "Course" title to "Test"

**Comment by amir-qayyum-khan** [comment]
Done

<img width="1168" alt="screen shot 2017-02-09 at 12 36 08 pm" src="https://cloud.githubusercontent.com/assets/10431250/22773506/5d070f14-eec4-11e6-8f3c-1ad75f795f69.png">

**Comment by aqdasrehman** [comment]
"Course" here is also be "Test"

![screen shot 2017-02-09 at 2 45 35 pm](https://cloud.githubusercontent.com/assets/13884387/22777880/95d441a6-eed6-11e6-9fdc-a824bf9032fa.png)

**Comment by amir-qayyum-khan** [comment]
can you take screenshot of exact location

**Comment by aqdasrehman** [comment]
Above is the screenshot of the exact location, question page.

**Comment by aqdasrehman** [comment]
![2017-02-11_2346](https://cloud.githubusercontent.com/assets/13884387/22856504/61e97aac-f0b4-11e6-989e-7f46afdb52e0.png)

**Comment by amir-qayyum-khan** [comment]
fixed

**Comment by aqdasrehman** [comment]
This is done. Closing
