### ISSUE TITLE
State of questions changed on previous/next button

### ISSUE THREAD

**Issue by aqdasrehman** [amir-qayyum-khan/edx-platform#62]
1. Submit answer for a question
![2017-02-11_0143](https://cloud.githubusercontent.com/assets/13884387/22843471/a021ea5c-effb-11e6-890a-fc2840aad886.png)

2. Click on the next button or question number then click previous button or the question you solved see the state of the question
![2017-02-11_0146](https://cloud.githubusercontent.com/assets/13884387/22843562/008568c4-effc-11e6-8b78-3690b1bedc89.png)

3. See the error message 
![2017-02-11_0147](https://cloud.githubusercontent.com/assets/13884387/22843604/22e61508-effc-11e6-8dda-e3574d5838e0.png)

**Comment by naeem91** [comment]
Fixed. Please verify

**Comment by aqdasrehman** [comment]
Done. Closing
