### ISSUE TITLE
Hide "Home" and "Discussion" tabs

### ISSUE THREAD

**Issue by aqdasrehman** [amir-qayyum-khan/edx-platform#7]
Please hide "Home" and "Discussion" tabs from the course

**Comment by amir-qayyum-khan** [comment]
@aqdasrehman please provide me cms url of course, so that i can hide home there

**Comment by aqdasrehman** [comment]
Links to the course: http://54.86.197.122/courses/course-v1:Arbisoft+Hiring_1+2017_1/info

**Comment by amir-qayyum-khan** [comment]
please verify

**Comment by aqdasrehman** [comment]
This is done, closing this issue. Although we need to change the Course text to Test and default landing on the test page.
