### ISSUE TITLE
Make all fields mandatory on http://test.arbisoft.com/register

### ISSUE THREAD

**Issue by raeeschachar** [amir-qayyum-khan/edx-platform#70]
Gender 
Year of Birth
Highest Level of Education Completed 
Mailing Address

Screenshot: https://screencast.com/t/buhm6omKYae

**Comment by wajeeha-khalid** [comment]
[relevant PR](https://github.com/amir-qayyum-khan/edx-platform/pulls)

**Comment by aqdasrehman** [comment]
This is Done.Closing
