### ISSUE TITLE
1st question already marked green even before attempting

### ISSUE THREAD

**Issue by aqdasrehman** [amir-qayyum-khan/edx-platform#73]
1. Register to a timed test 
2. Go to to timed test
3. On question 1 , I can see it already marked as green even if I hadn't attempt it

See attachement: 
![00000214](https://cloud.githubusercontent.com/assets/13884387/22928696/9703996c-f2d9-11e6-88a1-1e2683dc07ef.png)

**Comment by aqdasrehman** [comment]
@naeem91 Is this issue fixed ?

**Comment by naeem91** [comment]
Fixed. Please verify

**Comment by aqdasrehman** [comment]
This is done. Closing
