### ISSUE TITLE
Remove extra fields and tabs

### ISSUE THREAD

**Issue by aqdasrehman** [amir-qayyum-khan/edx-platform#75]
Please remove the extra fields and extra tabs that we don't need. See attachments:

<img width="1279" alt="00000541" src="https://cloud.githubusercontent.com/assets/13884387/22930282/453fe15a-f2e1-11e6-9522-48ef2b2ec411.png">
<img width="1279" alt="00000542" src="https://cloud.githubusercontent.com/assets/13884387/22930298/54b4468a-f2e1-11e6-8d60-d360548679f6.png">
<img width="1279" alt="00000543" src="https://cloud.githubusercontent.com/assets/13884387/22930314/6614d41c-f2e1-11e6-9239-1267522c252c.png">

**Comment by amir-qayyum-khan** [comment]
remove line 39 and 40 from this file
edx-platform/themes/arbisoft-nda/lms/templates/header.html

**Comment by aqdasrehman** [comment]
Done. Closing
