### ISSUE TITLE
Change title text on courses page

### ISSUE THREAD

**Issue by aisha-sajid** [amir-qayyum-khan/edx-platform#80]
PFA screenshot. Kindly edit the header text from _Lorem Ipsom..._ to the required text on the courses page

![screen shot 2017-02-15 at 1 04 48 pm](https://cloud.githubusercontent.com/assets/25361409/22965456/7e6a2b4a-f37f-11e6-9ba3-9900b28a5512.png)

**Comment by ayeshatariqmahmood** [comment]
We're ignoring this page, it will be hidden for the students
