### ISSUE TITLE
Timer clock is not working on Safari 

### ISSUE THREAD

**Issue by aqdasrehman** [amir-qayyum-khan/edx-platform#97]
Timer clock ticker is not working on Safari 

See attachement:

<img width="1279" alt="00000563" src="https://cloud.githubusercontent.com/assets/13884387/23013773/e51838c2-f44d-11e6-96a9-b1f2bab35f1b.png">

**Comment by aqdasrehman** [comment]
Also not working on Firefox Version 45. 
See attachement:

![screen shot 2017-02-16 at 12 40 15 pm](https://cloud.githubusercontent.com/assets/13884387/23015561/1d2254c6-f455-11e6-8c8e-fa031e839504.png)

**Comment by noraiz-anwar** [comment]
https://github.com/amir-qayyum-khan/edx-platform/pull/98

**Comment by amir-qayyum-khan** [comment]
need to deploy after 5

**Comment by noraiz-anwar** [comment]
sorry I didn't get it. 5?

**Comment by amir-qayyum-khan** [comment]
my personal notes, i will deploy this code after 5

**Comment by aqdasrehman** [comment]
Working on Safari, I will verify on Firefox version 45 and close this ticket.

**Comment by aqdasrehman** [comment]
This is done. Closing
